### ISSUE TITLE
Should not include <%-- --%>

### ISSUE THREAD

**Issue by lankymart** [jtjoo/vscode-classic-asp-extension#2]
This is the age old Classic ASP (asp) versus ASP.Net (aspx) server-side comments do not exist in Classic ASP see [Server-side comments: What's the equivalent of <%— --%> in ASP Classic?](https://stackoverflow.com/q/4431170/692942)

Should be removed from see [Comment on syntaxes/asp.html.tmLanguage.json - line 9](https://github.com/jtjoo/vscode-classic-asp-html/commit/71f936ab2ce79dd3f36e56d482a746fc0b225a38##commitcomment-23724915)

**Comment by jtjoo** [comment]
OK I removed it. Thanks ;)

https://github.com/jtjoo/vscode-classic-asp-html/commit/42392bd9ce9643e418c699c3bc0542a403385834
