### ISSUE TITLE
v0.0.4 Syntax Highlighting Issues

### ISSUE THREAD

**Issue by davidjaldred** [jtjoo/vscode-classic-asp-extension#5]
Left angle brackets '<' inside double or single quote marks cause syntax highlighting issues.

![asp](https://user-images.githubusercontent.com/33041809/32185185-6d033d10-bd96-11e7-9eb0-cd247415f3cc.PNG)
![asp2](https://user-images.githubusercontent.com/33041809/32185184-6ce9716e-bd96-11e7-9851-66a35155ca93.PNG)

Almost certain this wasn't an issue before the updates yesterday. Would take a look myself if I had the time.

Thanks man, nice to see your continued support on this extension 😊

**Comment by jtjoo** [comment]
In ASP single quote is not string quote but it is used for comment.
Thanks for your concern.
I'll close this issue

**Comment by jtjoo** [comment]
Ah.. you meant the color... I'll check it out. I am sorry.

**Comment by jtjoo** [comment]
I found problem.
It fixed on 0.0.6 !
Check it out and when you find another problem, let me know.
If there is no problem then please close this issue or tell me that I may close this issue.

**Comment by davidjaldred** [comment]
Thanks, it's working perfectly now!
Sorry I wasn't able to contribute.

**Comment by jtjoo** [comment]
Reporting an issue is also contribute. Thanks for your concern. Thank you!
