### ISSUE TITLE
Syntax Highlighting Issue

### ISSUE THREAD

**Issue by william-voyek** [jtjoo/vscode-classic-asp-extension#6]
In certain cases code within `<%` `%>` on a single line doesn't appear to highlight/color correctly.
![screenshot 2017-12-20 09 11 30](https://user-images.githubusercontent.com/989760/34219447-0e81f356-e566-11e7-9b36-2325d7ae6455.png)

**Comment by jtjoo** [comment]
I am so sorry too late answer.
I was in hospital that day.
I'll fix it next release.

I've lost my token access to publish next release.
When I find it, your problem will be fixed.

Thank you for your concern.
I will close this issue or you can close when you check next release.
So when you check next release (0.1.0), please comment here.

**Comment by fujitatakesh** [comment]
I found no highlighted syntax "End With" please apply. Thanks.

**Comment by jtjoo** [comment]
I added "End With". I will close this issue. If you find additional problem about this issue, reopen this issue or add more. Feedbacks are always welcome!
